import java.nio.file.Paths

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

plugins {
    id('java-library')
    id('jacoco')
    id('maven-publish')
}

if (propertyWithDefault("artifactType", null) == "spark")
{
    apply from: "$rootDir/gradle/common/publishing.gradle"
}

java {
    withJavadocJar()
    withSourcesJar()

    // Allows publishing the test jar
    registerFeature("test") {
        usingSourceSet(sourceSets.test)
    }
}

configurations {
    fourzero {
        description = 'Cassandra 4.0 dependency'
    }
    fourzeroBridge {
        description = 'Bridge to Cassandra 4.0'
    }
    fourzeroTypes {
        description = 'Cassandra 4.0 Data Types'
    }
    fourzeroSparkSql {
        description = 'Cassandra 4.0 SparkSQL Converter'
    }

    fivezero {
        description = 'Cassandra 5.0 dependency'
    }
    fivezeroBridge {
        description = 'Bridge to Cassandra 5.0'
    }
    fivezeroTypes {
        description = 'Cassandra 5.0 Data Types'
    }
    fivezeroSparkSql {
        description = 'Cassandra 5.0 SparkSQL Converter'
    }
}

dependencies {
    api(project(':cassandra-bridge'))

    implementation project(":cassandra-analytics-common")
    implementation project(":cassandra-analytics-sidecar-client")

    fourzero(project(path: ':cassandra-four-zero', configuration: 'shadow'))
    fourzeroBridge(project(path: ':cassandra-four-zero-bridge'))
    fourzeroTypes(project(path: ':cassandra-four-zero-types'))
    fourzeroSparkSql(project(path: ':cassandra-analytics-spark-four-zero-converter'))

    fivezero(project(path: ':cassandra-five-zero', configuration: 'shadow'))
    fivezeroBridge(project(path: ':cassandra-five-zero-bridge'))
    fivezeroTypes(project(path: ':cassandra-five-zero-types'))
    fivezeroSparkSql(project(path: ':cassandra-analytics-spark-five-zero-converter'))

    api(project(':cassandra-analytics-spark-converter'))

    // Including newer JNA which works with "Modern" Linux/GLIBC.
    // End users can exclude this and include their own if necessary.
    runtimeOnly(group: 'net.java.dev.jna', name: 'jna', version: "${jnaVersion}")
    runtimeOnly(group: 'net.java.dev.jna', name: 'jna-platform', version: "${jnaVersion}")

    if ("${scalaMajorVersion}" == "2.11") {
        implementation(group: 'org.scala-lang.modules', name: "scala-java8-compat_2.11", version: '1.0.1', transitive: false)
    }

    // aws sdk BOM + s3
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:netty-nio-client'
    implementation platform(group: 'software.amazon.awssdk', name:'bom', version:"${project.aswSdkVersion}")

    compileOnly(group: "${sparkGroupId}", name: "spark-core_${scalaMajorVersion}", version: "${project.rootProject.sparkVersion}")
    compileOnly(group: "${sparkGroupId}", name: "spark-sql_${scalaMajorVersion}", version: "${project.rootProject.sparkVersion}")

    testImplementation(group: 'com.google.guava', name: 'guava', version: '19.0')
    testImplementation(testFixtures(project(':cassandra-bridge')))
    testImplementation(project(':cassandra-analytics-spark-converter'))
    testImplementation(testFixtures(project(':cassandra-bridge')))
    testImplementation("org.junit.jupiter:junit-jupiter-api:${project.junitVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${project.junitVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:${project.junitVersion}")
    testImplementation("org.assertj:assertj-core:${assertjCoreVersion}")
    testImplementation(group: 'org.quicktheories', name: 'quicktheories', version: "${project.rootProject.quickTheoriesVersion}")
    testImplementation(group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.26')
    testImplementation(group: 'org.mockito', name: 'mockito-core', version: "${project.rootProject.mockitoVersion}")
    testImplementation(group: 'org.mockito', name: 'mockito-inline', version: "${project.rootProject.mockitoVersion}")
    testImplementation(group: "${sparkGroupId}", name: "spark-core_${scalaMajorVersion}", version: "${project.rootProject.sparkVersion}")
    testImplementation(group: "${sparkGroupId}", name: "spark-sql_${scalaMajorVersion}", version: "${project.rootProject.sparkVersion}")
    testImplementation(group: 'org.hamcrest', name: 'hamcrest', version: '2.2')
    testImplementation(group: 'org.openjdk.jmh', name: 'jmh-core', version: '1.33')
    testImplementation(group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.13')
    testImplementation(group: 'com.github.luben', name: 'zstd-jni', version: '1.5.0-4')
    testImplementation(group: 'org.xerial.snappy', name: 'snappy-java', version: '1.1.8.4')

    testRuntimeOnly(group: 'net.java.dev.jna', name: 'jna', version: "${jnaVersion}")
    testRuntimeOnly(group: 'net.java.dev.jna', name: 'jna-platform', version: "${jnaVersion}")
}

jar {
    dependsOn(configurations.fourzero)
    dependsOn(configurations.fourzeroBridge)
    dependsOn(configurations.fourzeroSparkSql)
    dependsOn(configurations.fourzeroTypes)

    dependsOn(configurations.fivezero)
    dependsOn(configurations.fivezeroBridge)
    dependsOn(configurations.fivezeroSparkSql)
    dependsOn(configurations.fivezeroTypes)

    writeBuildVersion(version, project.projectDir)

    exclude('META-INF/*')
    into('bridges') {
        from(configurations.fourzero.singleFile)
        from(configurations.fourzeroBridge.singleFile)
        from(configurations.fourzeroTypes.singleFile)
        from(configurations.fourzeroSparkSql.singleFile)

        from(configurations.fivezero.singleFile)
        from(configurations.fivezeroBridge.singleFile)
        from(configurations.fivezeroTypes.singleFile)
        from(configurations.fivezeroSparkSql.singleFile)
    }
}

// Tests tagged 'Sequential' do not run in parallel, to prevent OOM errors
// when running in CI environment.
tasks.register('testSequential', Test) {
    doFirst {
        if (JavaVersion.current().isJava11Compatible()) {
            def JDK11_OPTIONS = ['-Djdk.attach.allowAttachSelf=true',
                                 '--add-exports', 'java.base/jdk.internal.misc=ALL-UNNAMED',
                                 '--add-exports', 'java.base/jdk.internal.ref=ALL-UNNAMED',
                                 '--add-exports', 'java.base/sun.nio.ch=ALL-UNNAMED',
                                 '--add-exports', 'java.management.rmi/com.sun.jmx.remote.internal.rmi=ALL-UNNAMED',
                                 '--add-exports', 'java.rmi/sun.rmi.registry=ALL-UNNAMED',
                                 '--add-exports', 'java.rmi/sun.rmi.server=ALL-UNNAMED',
                                 '--add-exports', 'java.sql/java.sql=ALL-UNNAMED',
                                 '--add-opens', 'java.base/java.lang.module=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.loader=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.ref=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.reflect=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.math=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.module=ALL-UNNAMED',
                                 '--add-opens', 'java.base/jdk.internal.util.jar=ALL-UNNAMED',
                                 '--add-opens', 'jdk.management/com.sun.management.internal=ALL-UNNAMED']
            jvmArgs(JDK11_OPTIONS)
            println("JVM arguments for $project.name are $allJvmArgs")
        }
    }

    systemProperty "cassandra.analytics.bridges.sstable_format", System.getProperty("cassandra.analytics.bridges.sstable_format", "big")
    minHeapSize = '1024m'
    maxHeapSize = System.getenv('CORE_TEST_MAX_HEAP_SIZE') ?: '2048m'
    maxParallelForks = 1
    forkEvery = 1  // Enables different end-to-end test classes use Spark contexts with different configurations

    // Make it so unit tests run on a Jar with Cassandra bridge implementations built in
    dependsOn(tasks.jar)
    classpath += files(jar.archiveFile)

    useJUnitPlatform {
        includeTags 'Sequential'
    }

    reports {
        def destDir = Paths.get(rootProject.rootDir.absolutePath, "build", "test-reports", "core").toFile()
        junitXml {
            enabled true
            destination = destDir
        }
        html {
            enabled true
            destination = destDir
        }
    }

    testLogging {
        events "started", "passed", "skipped", "failed"
    }

    shouldRunAfter test
    finalizedBy jacocoTestReport // report is always generated after tests run
}

test {
    systemProperty "cassandra.analytics.bridges.sstable_format", System.getProperty("cassandra.analytics.bridges.sstable_format", "big")
    minHeapSize = '1024m'
    maxHeapSize = System.getenv('CORE_TEST_MAX_HEAP_SIZE') ?: '2048m'
    // TODO: revisit relaxing these resource constraints once we find the offending tests
    // maxParallelForks = System.getenv('CORE_MAX_PARALLEL_FORKS')?.toInteger()
    //                    ?: Math.max(Runtime.runtime.availableProcessors() * 2, 8)
    forkEvery = 1  // Enables different end-to-end test classes use Spark contexts with different configurations

    // Make it so unit tests run on a Jar with Cassandra bridge implementations built in
    dependsOn(tasks.jar)
    classpath += files(jar.archiveFile)

    useJUnitPlatform {
        excludeTags 'Sequential'
    }
    reports {
        def destDir = Paths.get(rootProject.rootDir.absolutePath, "build", "test-reports", "core").toFile()
        junitXml {
            enabled true
            destination = destDir
        }
        html {
            enabled true
            destination = destDir
        }
    }

    testLogging {
        events "started", "passed", "skipped", "failed"
    }

    finalizedBy jacocoTestReport // report is always generated after tests run
}

/* Start: JaCoCo check */
jacoco {
    toolVersion = '0.8.4'
}

jacocoTestReport {
    // collects the execution data from all test type tasks
    executionData tasks.withType(Test)
    reports {
        html.required = true
        html.destination(file("$buildDir/reports/jacocoHtml"))
        xml.required = true
        xml.destination(file("$buildDir/reports/jacocoXml"))
    }
}

jacocoTestCoverageVerification {
    dependsOn(tasks.testSequential)
    executionData(tasks.jacocoTestReport.executionData)
    violationRules {
        rule {
            limit {
                minimum = 0.5
            }
        }
    }
}

check {
    dependsOn(tasks.testSequential)
    dependsOn(tasks.jacocoTestCoverageVerification)
    finalizedBy(tasks.jacocoTestReport)
}
/* End: JaCoCo check */

private void writeBuildVersion(version, projectDir) {
    def prop = new Properties()
    prop.setProperty('build-version', "${version}")
    def hash = System.getenv('GIT_HASH') ?: 'unknown'
    prop.setProperty('build-rev', hash)
    def propFile = new File("${projectDir}/src/main/resources/cassandra-analytics-build.properties")
    propFile.createNewFile()
    prop.store(propFile.newWriter(), null)
    logger.info("Wrote to file={}, version={}, hash={}", propFile, version, hash)
}
